#!/bin/sh/
# A media access control address (MAC address) of a device is a unique
# identifier assigned to network interface controllers for communications
# at the data link layer of a network segment.
# Check : Settings > Network > Wi-Fi > Advanced : Mac adress
ifconfig p2p0 | grep "ether" | awk '{print $2}'
