#!/bin/sh/
# * * * * * command to be executed
# - - - - -
# | | | | |
# | | | | ----- Day of week (0 - 7) (Sunday=0 or 7)
# | | | ------- Month (1 - 12)
# | | --------- Day of month (1 - 31)
# | ----------- Hour (0 - 23)
# ------------- Minute (0 - 59)

# Type 'crontab -e'
# Add line : 0 4 * * 1 /bin/bash /path/02
# sh -c : Read from string. Necessary for sudo strings.
# Writing rights of update_script.log to be changed (chmod a+w)
sudo sh -c 'apt-get -qy update >> /var/log/update_script.log ; apt-get -qy upgrade >> /var/log/update_script.log ; apt-get -qy dist-upgrade >> /var/log/update_script.log'
