#!/bin/sh/
# * * * * * command to be executed
# - - - - -
# | | | | |
# | | | | ----- Day of week (0 - 7) (Sunday=0 or 7)
# | | | ------- Month (1 - 12)
# | | --------- Day of month (1 - 31)
# | ----------- Hour (0 - 23)
# ------------- Minute (0 - 59)

# Line to add in Crontab
# Type crontab -e
# 0 4 * * 1 /bin/bash /path/02
sudo apt-get update >> /var/log/update_script.log
sudo apt-get upgrade >> /var/log/update_script.log
